package com.tej.Worksphere.service.impl;

import java.io.ByteArrayOutputStream;

import org.springframework.stereotype.Service;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.tej.Worksphere.entity.Payroll;
import com.tej.Worksphere.exception.ResourceNotFoundException;
import com.tej.Worksphere.repository.PayrollRepository;
import com.tej.Worksphere.service.PdfService;

import lombok.RequiredArgsConstructor;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;

@Service
@RequiredArgsConstructor
public class PdfServiceImpl implements PdfService {

    private final PayrollRepository payrollRepository;

   @Override
public byte[] generatePayrollPdf(Long payrollId) {

    Payroll payroll = payrollRepository.findById(payrollId)
            .orElseThrow(() -> new ResourceNotFoundException(
                    "Payroll not found with id: " + payrollId));

    ByteArrayOutputStream out = new ByteArrayOutputStream();

    Document document = new Document();

    try {

        PdfWriter.getInstance(document, out);

        document.open();

        Font titleFont =
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);

        Font headingFont =
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);

        Font normalFont =
                FontFactory.getFont(FontFactory.HELVETICA, 12);

        Font boldFont =
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);

        // Title
        Paragraph title =
                new Paragraph("WORKSPHERE HRMS", titleFont);

        title.setAlignment(Paragraph.ALIGN_CENTER);

        document.add(title);

        document.add(new Paragraph(" "));

        // Heading
        Paragraph heading =
                new Paragraph("Salary Slip", headingFont);

        heading.setAlignment(Paragraph.ALIGN_CENTER);

        document.add(heading);

        document.add(new Paragraph(" "));

        // Employee Details
        document.add(new Paragraph(
                "Employee : "
                        + payroll.getEmployee().getFirstName()
                        + " "
                        + payroll.getEmployee().getLastName(),
                normalFont));

        document.add(new Paragraph(
                "Salary Month : "
                        + payroll.getSalaryMonth(),
                normalFont));

        document.add(new Paragraph(
                "Payment Date : "
                        + payroll.getPaymentDate(),
                normalFont));

        document.add(new Paragraph(" "));

        // Salary Details
        document.add(new Paragraph(
                "Basic Salary : ₹"
                        + payroll.getBasicSalary(),
                normalFont));

        document.add(new Paragraph(
                "HRA : ₹"
                        + payroll.getHra(),
                normalFont));

        document.add(new Paragraph(
                "Allowances : ₹"
                        + payroll.getAllowances(),
                normalFont));

        document.add(new Paragraph(
                "Bonus : ₹"
                        + payroll.getBonus(),
                normalFont));

        document.add(new Paragraph(
                "Deductions : ₹"
                        + payroll.getDeductions(),
                normalFont));

        document.add(new Paragraph(" "));

        // Net Salary
        document.add(new Paragraph(
                "Net Salary : ₹"
                        + payroll.getNetSalary(),
                boldFont));

        document.add(new Paragraph(" "));

        // Footer
        document.add(new Paragraph(
                "Generated by WorkSphere HRMS",
                normalFont));

        document.close();

    } catch (DocumentException e) {

        throw new RuntimeException("Error generating PDF", e);
    }

    return out.toByteArray();
}
}